env:
  browser: true
  es2021: true
extends:
  - plugin:react/jsx-runtime
  - standard-with-typescript
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
rules: {
    "react/react-in-jsx-scope": "off"
}