# Generated by Django 5.0 on 2023-12-11 01:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("crypto_station_api", "0006_trades"),
    ]

    operations = [
        migrations.RenameField(
            model_name="trades",
            old_name="order_price",
            new_name="trade_price",
        ),
    ]
