# Generated by Django 5.0 on 2023-12-10 21:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crypto_station_api", "0002_orders_expiration_tmstmp"),
    ]

    operations = [
        migrations.AddField(
            model_name="orders",
            name="insert_tmstmp",
            field=models.DateTimeField(
                default=datetime.date(2023, 1, 1),
                verbose_name="Record Insert Timestamp",
            ),
            preserve_default=False,
        ),
    ]
