# Generated by Django 5.0 on 2023-12-11 00:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("crypto_station_api", "0003_orders_insert_tmstmp"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Orders",
        ),
    ]
