CREATE OR REPLACE VIEW TRAINING_DATA.FORMATTED_DATA AS
SELECT OHLCV.CALENDAR_DT,
	OHLCV.PAIR_FORMATTED AS PAIR,
	OHLCV.OPEN,
	OHLCV.HIGH,
	OHLCV.LOW,
	OHLCV.CLOSE,
	OHLCV.HIGH / OHLCV.OPEN - 1 AS DAY_PEAK,
	OHLCV.LOW / OHLCV.OPEN - 1 AS DAY_DRAWDOWN,
	OHLCV.CLOSE / OHLCV.OPEN - 1 AS DAY_RETURN,
	OHLCV.VOLUME * OHLCV.CLOSE AS USD_VOLUME,
	KEY_LEVELS.FRACTAL_SUPPORT,
	CASE
	    WHEN OHLCV.LOW < KEY_LEVELS.FRACTAL_SUPPORT THEN 1
        ELSE 0
    END AS HAS_CROSSED_FRACTAL_SUPPORT,
	KEY_LEVELS.FRACTAL_RESISTANCE,
	CASE
        WHEN OHLCV.HIGH > KEY_LEVELS.FRACTAL_RESISTANCE THEN 1
        ELSE 0
    END AS HAS_CROSSED_FRACTAL_RESISTANCE,
	KEY_LEVELS.POC_SUPPORT,
	CASE
        WHEN OHLCV.LOW < KEY_LEVELS.POC_SUPPORT THEN 1
        ELSE 0
    END AS HAS_CROSSED_POC_SUPPORT,
	KEY_LEVELS.POC_RESISTANCE,
	CASE
        WHEN OHLCV.HIGH > KEY_LEVELS.POC_RESISTANCE THEN 1
        ELSE 0
    END AS HAS_CROSSED_POC_RESISTANCE,
	KEY_LEVELS.DISTANCE_TO_ATH,
	KEY_LEVELS.DISTANCE_TO_ATL
FROM TRAINING_DATA.OHLCV
LEFT JOIN TRAINING_DATA.KEY_LEVELS ON OHLCV.PAIR = KEY_LEVELS.PAIR
AND OHLCV.CALENDAR_DT = KEY_LEVELS.CALENDAR_DT
ORDER BY OHLCV.CALENDAR_DT