CREATE OR REPLACE VIEW TRAINING_DATA.FORMATTED_DATA AS
SELECT OHLCV.CALENDAR_DT,
	OHLCV.PAIR_FORMATTED AS PAIR,
	OHLCV.OPEN,
	OHLCV.HIGH,
	OHLCV.LOW,
	OHLCV.CLOSE,
	OHLCV.HIGH / OHLCV.OPEN - 1 AS DAY_PEAK,
	OHLCV.LOW / OHLCV.OPEN - 1 AS DAY_DRADOWN,
	OHLCV.CLOSE / OHLCV.OPEN - 1 AS DAY_RETURN,
	OHLCV.VOLUME * OHLCV.CLOSE AS USD_VOLUME,
	KEY_LEVELS.FRACTAL_SUPPORT,
	KEY_LEVELS.FRACTAL_RESISTANCE,
	KEY_LEVELS.POC_SUPPORT,
	KEY_LEVELS.POC_RESISTANCE,
	KEY_LEVELS.DISTANCE_TO_ATH,
	KEY_LEVELS.DISTANCE_TO_ATL
FROM TRAINING_DATA.OHLCV
LEFT JOIN TRAINING_DATA.KEY_LEVELS ON OHLCV.PAIR = KEY_LEVELS.PAIR
AND OHLCV.CALENDAR_DT = KEY_LEVELS.CALENDAR_DT
ORDER BY OHLCV.CALENDAR_DT